name: Run repo-map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  repo-map:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade .
    - name: Run repo-map
      run: repo-map .
    - name: Upload repo-map output
      uses: actions/upload-artifact@v3
      with:
        name: repo-map-output
        path: repo_map.json
