name: Run repo-map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  repo-map:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade .
    - name: Run repo-map
      run: |
        pwd
        ls -la
        repo-map --help
        repo-map . | tee repo_map.txt
    - name: Upload repo-map output
      uses: actions/upload-artifact@v4
      with:
        name: repo-map-output
        path: repo_map.txt
